config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include(('crm.urls', 'config'), namespace='crm')),
    path('sales_manager/', include(('sales_manager.urls', 'config'), namespace='sales_manager')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

sales_manager/urls.py
from django.urls import path
from .views import sales_manager, add_client

urlpatterns = [
    path('', sales_manager, name='sales_manager'),
    path('add_client/', add_client, name='add_client'),  # Это имя маршрута
]

crm/models.py
from django.db import models

# Create your models here.

sales_manager/models.py
from django.db import models


class Client(models.Model):
    name = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=15)
    sales_channel = models.CharField(max_length=255)
    course = models.CharField(max_length=255)
    birth_date = models.DateField()


class Column(models.Model):
    name = models.CharField(max_length=255)
    clients = models.ManyToManyField(Client, related_name='columns', blank=True)


class Direction (models.Model):
    name = models.CharField(max_length=255, unique=True)
    color = models.CharField(max_length=7, default='#000000')

crm/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

sales_manager/views.py
from django.shortcuts import render, redirect
from .models import Column, Client, Direction


def sales_manager(request):
    columns = Column.objects.all()
    clients = Client.objects.all()
    print(clients)  # Добавим вывод для отладки
    return render(request, 'sales_manager_panel.html', {'columns': columns, 'clients': clients})


def add_client(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        surname = request.POST.get('surname')
        phone_number = request.POST.get('phone_number')
        sales_channel = request.POST.get('sales_channel')
        course = request.POST.get('course')
        birth_date = request.POST.get('birth_date')

        new_client = Client.objects.create(
            name=name,
            surname=surname,
            phone_number=phone_number,
            sales_channel=sales_channel,
            course=course,
            birth_date=birth_date
        )

        return redirect('sales_manager:sales_manager')

    return render(request, 'sales_manager_panel.html')


def your_view(request):
    directions = Direction.objects.all()
    return render(request, 'sales_manager_panel.html', {'direction': directions})

crm/templates/home.html
{% load static from static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>crm</title>
{#    <link rel="stylesheet" href="{% static 'bulma.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'style.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'bulma.min.css' %}">#}
</head>
<body>
<section id="main" class="hero is-link is-violet is-fullheight">
    <div class="hero-head">
        <nav class="navbar">
            <div class="container">
                <div class="navbar-brand">
                    <a href="/home" class="navbar-item">
                        <img src="{% static 'img/logo_white.png' %}" alt="Logo">
                    </a>

                    <span class="navbar-burger burger">
                        <span></span>
                        <span></span>
                        <span></span>
                    </span>
                </div>

                <div class="navbar-menu">
                    <div class="navbar-end">
                        <a href="#main" class="navbar-item">Главная</a>
                        <a href="#Возможности" class="navbar-item">Возможности</a>
                        <a href="#Внедрение" class="navbar-item">Внедрение</a>
                        <a href="#" class="navbar-item">Цены</a>
                        <a href="#" class="navbar-item">Отзывы</a>
                        <a href="#" class="navbar-item">Документация</a>
                    </div>
                </div>
            </div>
        </nav>
    </div>

    <div class="hero-body">
        <div class="container">
            <div class="columns is-vcentered">
                <div class="column">
                    <img src="{% static 'img/Humaaans - 3 Characters.svg' %}" width="100%" alt="">
                </div>

                <div class="column is-5-desktop is-offset-1-desktop">
                    <h1 class="title is-1">
                        Управляйте учебным центром
                        ЛЕГКО с помощью CRM
                    </h1>

                    <h2 class="subtitle">
                        Автоматизируйте бизнес процессы, стройте эффективный отдел продаж для учебного центра.
                    </h2>
                </div>
            </div>
        </div>
    </div>
</section>

<br>

<h2 class="title is-5 has-text-centered has-text-Danger">
    CRM NEO
</h2>

<h1 class="title is-2 has-text-centered has-text-black">
    Какие задачи решаем?
</h1>
<h3 class="title is-6 has-text-centered has-text-Grey light">
    <p>Введите бизнес с удовольствием, а рутину оставьте CRM NEO</p>
</h3>

<section class="section" id="Возможности">
        <article class="problems-wrapper light-bg">
                <div class="columns is-multiline features">
                    <div class="column is-4">
                        <div class="icon">
                            <img src="{% static 'img/icon_funnel (1).svg' %}" width="" alt="">
                        </div>
                        <h4><b>Систематизация воронки продаж</b></h4>
                        <p>Создайте воронку для оценки эффективности взаимодействия с клиентом ― от момента знакомства с продуктом до заключения сделки.</p>
                    </div>

                    <div class="column is-4">
                        <div class="icon">
                            <img src="{% static 'img/icon_finance.svg'%}" alt="">
                        </div>
                        <h4><b>Управление финансами</b></h4>
                        <p>Автоматизируйте учет финансов и освободите драгоценное время. Следите за потоком ваших денег в реальном времени.</p>
                    </div>

                    <div class="column is-4">
                        <div class="icon">
                            <img src="{% static 'img/icon_personnel.svg' %}" alt="">
                        </div>
                        <h4><b>Контроль персонала</b></h4>
                        <p>Нудный процесс расчета зарплаты оставьте в прошлом. CRM NEO, исходя из ваших требований, сама рассчитает доход сотрудника.</p>
                    </div>

                    <div class="column is-4">
                        <div class="icon">
                            <img src="{% static 'img/icon_group.svg' %}" alt="">
                        </div>
                        <h4><b>Организация групп</b></h4>
                        <p>Гибкая система добавления новых групп и ведения их учета. Добавляйте учеников в два клика и перетаскивайте из группы в группу легким движением мышки.</p>
                    </div>

                    <div class="column is-4">
                        <div class="icon">
                            <img src="{% static 'img/icon_stats.svg' %}" alt="">
                        </div>
                        <h4><b>Статистика</b></h4>
                        <p>CRM NEO не будет вам врать. Она покажет только реальные данные, которые вы сможете использовать, чтобы построить верный путь для бизнеса.</p>
                    </div>
                    <div class="column is-4">
                        <div class="icon">
                            <img src="{%static 'img/icon_marketing.svg' %}" alt="">
                        </div>
                        <h4><b>Маркетинг и каналы продаж</b></h4>
                        <p>CRM NEO скажет точно, какая реклама реально продвигает бизнес, а какая просто не стоит вложенных денег. На остаток купите мороженное.</p>
                    </div>
                </div>
            </div>
        </article>
</section>

<br>

<h2 class="title is-5 has-text-centered has-text-Danger">
    CRM NEO
</h2>

<h1 class="title is-2 has-text-centered has-text-black">
    Как внедрить CRM NEO?
</h1>
<h3 class="title is-6 has-text-centered has-text-Grey light">
    <p>Просто, как два пальца об асвальт</p>
</h3>

{% block content %}
{% endblock %}
<footer class="section">
    <div class="content has-text-centered">
        <p>
            <strong><a href="/" class="has-text-dark">Monday Academy</a></strong>
            Подразделение
            <a href="https://mondaylabs.tech">OOO "Monday Labs"</a>.<br>
        </p>
    </div>
</footer>
</body>

sales_manager/templates/sales_manager_panel.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sales Manager</title>
    <link rel="stylesheet" href="{% static 'static/style.css' %}">
</head>

<body>
    <div class="navbar">
        <a href="#">Главная</a>
        <a href="#">О нас</a>
        <a href="#">Контакты</a>
    </div>

    <div class="container">
        <h1>Sales Manager</h1>

        <div class="sales-manager-columns">
            {% for column in columns %}
            <div class="custom-sales-column" style="background-color: {{ column.direction.color }}">
                <h2>{{ column.direction.name }}</h2>
                <ul class="client-list" id="column_{{ column.id }}">
                    {% for client in column.clients.all %}
                    <li>{{ client.name }} {{ client.surname }}</li>
                        {% for directions in  columns.diretions.all %}
                            {% endfor %}
                    {% endfor %}
                </ul>
                <button class="add-client-btn" data-column="{{ column.id }}">+add</button>
            </div>
            {% endfor %}
        </div>

        <div id="addClientModal" class="modal">
            <div class="modal-content">
                <span class="close">&times;</span>
                <form id="addClientForm" method="post" action="{% url 'sales_manager:add_client' %}">
                    {% csrf_token %}
                    <input type="text" name="name" placeholder="Name" required>
                    <input type="text" name="surname" placeholder="Surname" required>
                    <input type="text" name="phone_number" placeholder="Phone Number" required>
                    <input type="text" name="sales_channel" placeholder="Sales Channel" required>
                    <input type="text" name="description"placeholder="description" required>
                    <input type="text" name="course" placeholder="Course" required>
                    <input type="date" name="birth_date" placeholder="Birth Date" required>
                    <input type="submit" value="Add Client">
                </form>
            </div>
        </div>
    </div>

    <div class="clients">
        {% for client in clients %}
        <div class="client-card">
            {{ client.name }} {{ client.surname }}
        </div>
        {% endfor %}
    </div>

    <script>
        // Modal logic
        const modal = document.getElementById('addClientModal');
        const btns = document.querySelectorAll('.add-client-btn');
        const span = document.querySelector('.close');

        btns.forEach(btn => {
            btn.addEventListener('click', function () {
                modal.style.display = 'block';
            });
        });

        span.addEventListener('click', function () {
            modal.style.display = 'none';
        });

        window.addEventListener('click', function (event) {
            if (event.target === modal) {
                modal.style.display = 'none';
            }
        });
    </script>

</body>

</html>